# Generated by Django 5.1.2 on 2024-10-27 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_address_options_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='addresses',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
